module.exports = {
  // Meta redirects.
  '/releases/latest': '/releases/2.9.x',

  // External redirects.
  '/reference/roadmap': 'https://nats.io/about#roadmap',
  '/reference/contributing': 'https://nats.io/contributing',

  // v1 -> v2 redirects.
  '/nats-concepts/overview': '/intro/overview',
  '/nats-concepts/overview/compare-nats': '/intro/overview',
  '/nats-concepts/what-is-nats': '/intro/overview',
  '/nats-concepts/what-is-nats/walkthrough_setup': '/intro/start',
  '/nats-concepts/subjects': '/concepts/subjects',
  '/nats-concepts/core-nats/pubsub': '/concepts/messaging',
  '/nats-concepts/core-nats/reqreply': '/concepts/messaging',
  '/nats-concepts/core-nats/queue': '/concepts/messaging',
  '/nats-concepts/jetstream': '/concepts/streaming',
  '/nats-concepts/jetstream/streams': '/concepts/streaming',
  '/nats-concepts/jetstream/consumers': '/concepts/streaming',
  '/nats-concepts/jetstream/consumers/example_configuration': '/concepts/streaming',
  '/nats-concepts/jetstream/js_walkthrough': '/concepts/streaming',
  '/nats-concepts/jetstream/key-value-store': '/concepts/key-value',
  '/nats-concepts/jetstream/key-value-store/kv_walkthrough': '/concepts/key-value',
  '/nats-concepts/jetstream/obj_store': '/concepts/object-store',
  '/nats-concepts/jetstream/obj_store/obj_walkthrough': '/concepts/object-store',
  '/nats-concepts/core-nats/pubsub/pubsub_walkthrough': '/intro/start',
  '/nats-concepts/core-nats/reqreply/reqreply_walkthrough': '/intro/start',
  '/nats-concepts/core-nats/queue/queue_walkthrough': '/intro/start',
  '/reference/reference-protocols': '/reference/protocols',
  '/reference/reference-protocols/nats-protocol': '/reference/protocols/client',
  '/reference/reference-protocols/nats-server-protocol': '/reference/protocols/cluster',
  '/reference/reference-protocols/nats_api_reference': '/reference/protocols/client/jetstream',
  '/release_notes/whats_new': '/release-notes/latest',
  '/release_notes/whats_new_22': '/release-notes/2.2.x',
  '/release_notes/whats_new_20': '/release-notes/2.0.x',

  // Legacy redirects. These are being maintained since old links, blog posts, etc. may
  // still reference these paths.
  '/nats-tools/nas': '/legacy/nas/README',
  '/nats-tools/nas/dir_store': '/legacy/nas/dir_store',
  '/nats-tools/nas/inspecting_jwts': '/legacy/nas/inspecting_jwts',
  '/nats-tools/nas/nas_conf': '/legacy/nas/nas_conf',
  '/nats-tools/nas/notifications': '/legacy/nas/notifications',
  '/developing-with-nats-streaming/acks': '/legacy/stan/developing-with-nats-streaming/acks',
  '/developing-with-nats-streaming/connecting': '/legacy/stan/developing-with-nats-streaming/connecting',
  '/developing-with-nats-streaming/durables': '/legacy/stan/developing-with-nats-streaming/durables',
  '/developing-with-nats-streaming/protocol': '/legacy/stan/developing-with-nats-streaming/protocol',
  '/developing-with-nats-streaming/publishing': '/legacy/stan/developing-with-nats-streaming/publishing',
  '/developing-with-nats-streaming/queues': '/legacy/stan/developing-with-nats-streaming/queues',
  '/developing-with-nats-streaming/receiving': '/legacy/stan/developing-with-nats-streaming/receiving',
  '/developing-with-nats-streaming/streaming': '/legacy/stan/developing-with-nats-streaming/streaming',
  '/nats-streaming-concepts/channels': '/legacy/stan/nats-streaming-concepts/channels',
  '/nats-streaming-concepts/channels/message-log':
    '/legacy/stan/nats-streaming-concepts/channels/message-log',
  '/nats-streaming-concepts/channels/subscriptions':
    '/legacy/stan/nats-streaming-concepts/channels/subscriptions',
  '/nats-streaming-concepts/channels/subscriptions/durable':
    '/legacy/stan/nats-streaming-concepts/channels/subscriptions/durable',
  '/nats-streaming-concepts/channels/subscriptions/queue-group':
    '/legacy/stan/nats-streaming-concepts/channels/subscriptions/queue-group',
  '/nats-streaming-concepts/channels/subscriptions/redelivery':
    '/legacy/stan/nats-streaming-concepts/channels/subscriptions/redelivery',
  '/nats-streaming-concepts/channels/subscriptions/regular':
    '/legacy/stan/nats-streaming-concepts/channels/subscriptions/regular',
  '/nats-streaming-concepts/client-connections': '/legacy/stan/nats-streaming-concepts/client-connections',
  '/nats-streaming-concepts/clustering': '/legacy/stan/nats-streaming-concepts/clustering',
  '/nats-streaming-concepts/clustering/auto-configuration':
    '/legacy/stan/nats-streaming-concepts/clustering/auto-configuration',
  '/nats-streaming-concepts/clustering/configuration':
    '/legacy/stan/nats-streaming-concepts/clustering/configuration',
  '/nats-streaming-concepts/clustering/containers':
    '/legacy/stan/nats-streaming-concepts/clustering/containers',
  '/nats-streaming-concepts/clustering/supported-stores':
    '/legacy/stan/nats-streaming-concepts/clustering/supported-stores',
  '/nats-streaming-concepts/ft': '/legacy/stan/nats-streaming-concepts/ft',
  '/nats-streaming-concepts/ft/active-server': '/legacy/stan/nats-streaming-concepts/ft/active-server',
  '/nats-streaming-concepts/ft/failover': '/legacy/stan/nats-streaming-concepts/ft/failover',
  '/nats-streaming-concepts/ft/shared-state': '/legacy/stan/nats-streaming-concepts/ft/shared-state',
  '/nats-streaming-concepts/ft/standby-server': '/legacy/stan/nats-streaming-concepts/ft/standby-server',
  '/nats-streaming-concepts/intro': '/legacy/stan/nats-streaming-concepts/intro',
  '/nats-streaming-concepts/monitoring': '/legacy/stan/nats-streaming-concepts/monitoring',
  '/nats-streaming-concepts/monitoring/endpoints':
    '/legacy/stan/nats-streaming-concepts/monitoring/endpoints',
  '/nats-streaming-concepts/partitioning': '/legacy/stan/nats-streaming-concepts/partitioning',
  '/nats-streaming-concepts/relation-to-nats': '/legacy/stan/nats-streaming-concepts/relation-to-nats',
  '/nats-streaming-concepts/store-encryption': '/legacy/stan/nats-streaming-concepts/store-encryption',
  '/nats-streaming-concepts/store-interface': '/legacy/stan/nats-streaming-concepts/store-interface',
  '/nats-streaming-server/changes': '.legacy/stan/nats-streaming-server/changes',
  '/nats-streaming-server/install': '.legacy/stan/nats-streaming-server/install',
  '/nats-streaming-server/run': '.legacy/stan/nats-streaming-server/run',
  '/nats-streaming-server/configuring/README': '.legacy/stan/nats-streaming-server/configuring',
  '/nats-streaming-server/configuring/line': '.legacy/stan/nats-streaming-server/configuring/line',
  '/nats-streaming-server/configuring/cfgfile': '.legacy/stan/nats-streaming-server/configuring/cfgfile',
  '/nats-streaming-server/configuring/storelimits':
    '.legacy/stan/nats-streaming-server/configuring/storelimits',
  '/nats-streaming-server/configuring/persistence/README':
    '.legacy/stan/nats-streaming-server/configuring/persistence',
  '/nats-streaming-server/configuring/persistence/file_store':
    '.legacy/stan/nats-streaming-server/configuring/persistence/file_store',
  '/nats-streaming-server/configuring/persistence/sql_store':
    '.legacy/stan/nats-streaming-server/configuring/persistence/sql_store',
  '/nats-streaming-server/configuring/tls': '.legacy/stan/nats-streaming-server/configuring/tls',
  '/nats-streaming-server/process-signaling': '.legacy/stan/nats-streaming-server/process-signaling',
  '/nats-streaming-server/windows-service': '.legacy/stan/nats-streaming-server/windows-service',
  '/nats-streaming-server/embedding': '.legacy/stan/nats-streaming-server/embedding',
  '/nats-streaming-server/swarm': '.legacy/stan/nats-streaming-server/swarm',
  '/nats-streaming-server/kubernetes/stan-kubernetes':
    '.legacy/stan/nats-streaming-server/kubernetes/stan-kubernetes',
  '/nats-streaming-server/kubernetes/stan-ft-k8s-aws':
    '.legacy/stan/nats-streaming-server/kubernetes/stan-ft-k8s-aws',
  '/nats-concepts/pubsub': '/nats-concepts/core-nats/publish-subscribe/pubsub',
  '/walkthrough/pubsub': '/nats-concepts/core-nats/publish-subscribe/pubsub_walkthrough',
  '/nats-concepts/queue': '/nats-concepts/core-nats/queue-groups/queue',
  '/walkthrough/queues': '/nats-concepts/core-nats/queue-groups/queues_walkthrough',
  '/nats-concepts/core_nats': '/nats-concepts/core-nats',
  '/nats-concepts/reqreply': '/nats-concepts/core-nats/request-reply/reqreply',
  '/walkthrough/reqreply': '/nats-concepts/core-nats/request-reply/reqreply_walkthrough',
  '/jetstream': '/nats-concepts/jetstream',
  '/jetstream/concepts/consumers': '/nats-concepts/jetstream/consumers',
  '/jetstream/concepts/configuration': '/nats-concepts/jetstream/example_configuration',
  '/walkthrough/js': '/nats-concepts/jetstream/js_walkthrough',
  '/walkthrough/kv': '/nats-concepts/jetstream/key-value-store/kv_walkthrough',
  '/nats-concepts/kv_store': '/nats-concepts/jetstream/key-value-store',
  '/nats-concepts/jetstream': '/nats-concepts/jetstream',
  '/jetstream/concepts/streams': '/nats-concepts/jetstream/streams',
  '/compare-nats': '/nats-concepts/overview/compare-nats',
  '/nats-concepts/intro': '/nats-concepts/what-is-nats',
  '/walkthrough/walkthrough_setup': '/nats-concepts/what-is-nats/walkthrough_setup',
  '/faq': '/reference/faq',
  '/nats-protocol/nats-protocol-demo': '/reference/nats-protocol/nats-protocol-demo',
  '/nats-protocol/nats-protocol': '/reference/nats-protocol/nats-protocol',
  '/nats-protocol/nats-protocol/nats-client-dev': '/reference/nats-protocol/nats-protocol/nats-client-dev',
  '/nats-protocol/nats-server-protocol': '/reference/nats-protocol/nats-server-protocol',
  '/whats_new_20': '/release_notes/whats_new_20',
  '/whats_new_22': '/release_notes/whats_new_22',
  '/nats-server/clients': '/running-a-nats-service/clients',
  '/nats-server/configuration': '/running-a-nats-service/configuration',
  '/nats-server/configuration/clustering': '/running-a-nats-service/configuration/clustering',
  '/nats-server/configuration/clustering/cluster_config':
    '/running-a-nats-service/configuration/clustering/cluster_config',
  '/nats-server/configuration/clustering/cluster_tls':
    '/running-a-nats-service/configuration/clustering/cluster_tls',
  '/jetstream/clustering': '/running-a-nats-service/configuration/clustering/jetstream_clustering',
  '/jetstream/clustering/administration':
    '/running-a-nats-service/configuration/clustering/jetstream_clustering/administration',
  '/nats-server/configuration/configuring_subject_mapping':
    '/running-a-nats-service/configuration/configuring_subject_mapping',
  '/nats-server/configuration/gateways': '/running-a-nats-service/configuration/gateways',
  '/nats-server/configuration/gateways/gateway': '/running-a-nats-service/configuration/gateways/gateway',
  '/jetstream/configuration_mgmt':
    '/running-a-nats-service/configuration/jetstream-config/configuration_mgmt',
  '/jetstream/configuration_mgmt/github_actions':
    '/running-a-nats-service/configuration/jetstream-config/configuration_mgmt/github_actions',
  '/jetstream/configuration_mgmt/kubernetes_controller':
    '/running-a-nats-service/configuration/jetstream-config/configuration_mgmt/kubernetes_controller',
  '/jetstream/configuration_mgmt/nats-admin-cli':
    '/running-a-nats-service/configuration/jetstream-config/configuration_mgmt/nats-admin-cli',
  '/jetstream/configuration_mgmt/terraform':
    '/running-a-nats-service/configuration/jetstream-config/configuration_mgmt/terraform',
  '/jetstream/resource_management':
    '/running-a-nats-service/configuration/jetstream-config/resource_management',
  '/nats-server/configuration/leafnodes': '/running-a-nats-service/configuration/leafnodes',
  '/jetstream/leafnodes': '/running-a-nats-service/configuration/leafnodes/jetstream_leafnodes',
  '/nats-server/configuration/leafnodes/leafnode_conf':
    '/running-a-nats-service/configuration/leafnodes/leafnode_conf',
  '/nats-server/configuration/logging': '/running-a-nats-service/configuration/logging',
  '/nats-server/configuration/monitoring': '/running-a-nats-service/configuration/monitoring',
  '/nats-server/configuration/mqtt': '/running-a-nats-service/configuration/mqtt',
  '/nats-server/configuration/mqtt/mqtt_conf': '/running-a-nats-service/configuration/mqtt/mqtt_conf',
  '/nats-server/configuration/mqtt/mqtt_config': '/running-a-nats-service/configuration/mqtt/mqtt_config',
  '/nats-server/configuration/ocsp': '/running-a-nats-service/configuration/ocsp',
  '/nats-server/configuration/securing_nats/accounts':
    '/running-a-nats-service/configuration/securing_nats/accounts',
  '/nats-server/configuration/securing_nats/auth_intro':
    '/running-a-nats-service/configuration/securing_nats/auth_intro',
  '/nats-server/configuration/securing_nats/auth_intro/auth_timeout':
    '/running-a-nats-service/configuration/securing_nats/auth_intro/auth_timeout',
  '/nats-server/configuration/securing_nats/auth_intro/nkey_auth':
    '/running-a-nats-service/configuration/securing_nats/auth_intro/nkey_auth',
  '/nats-server/configuration/securing_nats/auth_intro/tls_mutual_auth':
    '/running-a-nats-service/configuration/securing_nats/auth_intro/tls_mutual_auth',
  '/nats-server/configuration/securing_nats/auth_intro/tokens':
    '/running-a-nats-service/configuration/securing_nats/auth_intro/tokens',
  '/nats-server/configuration/securing_nats/auth_intro/username_password':
    '/running-a-nats-service/configuration/securing_nats/auth_intro/username_password',
  '/nats-server/configuration/securing_nats/authorization':
    '/running-a-nats-service/configuration/securing_nats/authorization',
  '/nats-server/configuration/securing_nats/jwt': '/running-a-nats-service/configuration/securing_nats/jwt',
  '/nats-server/configuration/securing_nats/jwt/jwt_nkey_auth':
    '/running-a-nats-service/configuration/securing_nats/jwt/jwt_nkey_auth',
  '/nats-server/configuration/securing_nats/jwt/mem_resolver':
    '/running-a-nats-service/configuration/securing_nats/jwt/mem_resolver',
  '/nats-server/configuration/securing_nats/jwt/resolver':
    '/running-a-nats-service/configuration/securing_nats/jwt/resolver',
  '/nats-server/configuration/securing_nats/tls': '/running-a-nats-service/configuration/securing_nats/tls',
  '/nats-server/configuration/sys_accounts': '/running-a-nats-service/configuration/sys_accounts',
  '/nats-server/configuration/sys_accounts/sys_accounts':
    '/running-a-nats-service/configuration/sys_accounts/sys_accounts',
  '/nats-server/configuration/websocket': '/running-a-nats-service/configuration/websocket',
  '/nats-server/configuration/websocket/websocket_conf':
    '/running-a-nats-service/configuration/websocket/websocket_conf',
  '/nats-server/installation': '/running-a-nats-service/installation',
  '/running-nats-intro': '/running-a-nats-service/introduction',
  '/nats-on-kubernetes/create-k8s-cluster': '/running-a-nats-service/nats-on-kubernetes/create-k8s-cluster',
  '/nats-on-kubernetes/from-zero-to-leafnodes':
    '/running-a-nats-service/nats-on-kubernetes/from-zero-to-leafnodes',
  '/nats-on-kubernetes/helm-charts': '/running-a-nats-service/nats-on-kubernetes/helm-charts',
  '/nats-on-kubernetes/minimal-setup': '/running-a-nats-service/nats-on-kubernetes/minimal-setup',
  '/nats-on-kubernetes/nats-cluster-and-cert-manager':
    '/running-a-nats-service/nats-on-kubernetes/nats-cluster-and-cert-manager',
  '/nats-on-kubernetes/nats-external-nlb': '/running-a-nats-service/nats-on-kubernetes/nats-external-nlb',
  '/nats-on-kubernetes/nats-kubernetes': '/running-a-nats-service/nats-on-kubernetes/nats-kubernetes',
  '/nats-on-kubernetes/operator-tls-setup-with-cfssl':
    '/running-a-nats-service/nats-on-kubernetes/operator-tls-setup-with-cfssl',
  '/nats-on-kubernetes/super-cluster-on-digital-ocean':
    '/running-a-nats-service/nats-on-kubernetes/super-cluster-on-digital-ocean',
  '/jetstream/administration': '/running-a-nats-service/nats_admin/jetstream_admin',
  '/jetstream/administration/account': '/running-a-nats-service/nats_admin/jetstream_admin/account',
  '/jetstream/administration/consumers': '/running-a-nats-service/nats_admin/jetstream_admin/consumers',
  '/jetstream/disaster_recovery': '/running-a-nats-service/nats_admin/jetstream_admin/disaster_recovery',
  '/jetstream/encryption_at_rest': '/running-a-nats-service/nats_admin/jetstream_admin/encryption_at_rest',
  '/jetstream/administration/naming': '/running-a-nats-service/nats_admin/jetstream_admin/naming',
  '/jetstream/replication': '/running-a-nats-service/nats_admin/jetstream_admin/replication',
  '/jetstream/administration/streams': '/running-a-nats-service/nats_admin/jetstream_admin/streams',
  '/nats-server/nats_admin/lame_duck_mode': '/running-a-nats-service/nats_admin/lame_duck_mode',
  '/jetstream/monitoring': '/running-a-nats-service/nats_admin/monitoring/monitoring_jetstream',
  '/nats-server/nats_admin/monitoring': '/running-a-nats-service/nats_admin/monitoring',
  '/nats-server/nats_admin/signals': '/running-a-nats-service/nats_admin/signals',
  '/nats-server/nats_admin/slow_consumers': '/running-a-nats-service/nats_admin/slow_consumers',
  '/nats-server/nats_admin/upgrading_cluster': '/running-a-nats-service/nats_admin/upgrading_cluster',
  '/nats-server/running': '/running-a-nats-service/running',
  '/nats-server/flags': '/running-a-nats-service/running/flags',
  '/nats-server/nats_docker': '/running-a-nats-service/running/nats_docker',
  '/nats-server/nats_docker/docker_swarm': '/running-a-nats-service/running/nats_docker/docker_swarm',
  '/jetstream/getting_started/using_docker': '/running-a-nats-service/running/nats_docker/jetstream_docker',
  '/nats-server/nats_docker/nats-docker-tutorial':
    '/running-a-nats-service/running/nats_docker/nats-docker-tutorial',
  '/nats-server/nats_docker/ngs-docker-python':
    '/running-a-nats-service/running/nats_docker/ngs-docker-python',
  '/nats-server/running/windows_srv': '/running-a-nats-service/running/windows_srv',
  '/developing-with-nats/connecting': '/using-nats/developing-with-nats/connecting',
  '/developing-with-nats/connecting/cluster': '/using-nats/developing-with-nats/connecting/cluster',
  '/developing-with-nats/connecting/connect_timeout':
    '/using-nats/developing-with-nats/connecting/connect_timeout',
  '/developing-with-nats/connecting/default_server':
    '/using-nats/developing-with-nats/connecting/default_server',
  '/developing-with-nats/connecting/misc': '/using-nats/developing-with-nats/connecting/misc',
  '/developing-with-nats/connecting/name': '/using-nats/developing-with-nats/connecting/name',
  '/developing-with-nats/connecting/noecho': '/using-nats/developing-with-nats/connecting/noecho',
  '/developing-with-nats/connecting/pingpong': '/using-nats/developing-with-nats/connecting/pingpong',
  '/developing-with-nats/connecting/specific_server':
    '/using-nats/developing-with-nats/connecting/specific_server',
  '/developing-with-nats/developer': '/using-nats/developing-with-nats/developer',
  '/developing-with-nats/events': '/using-nats/developing-with-nats/events',
  '/developing-with-nats/events/events': '/using-nats/developing-with-nats/events/events',
  '/developing-with-nats/events/slow': '/using-nats/developing-with-nats/events/slow',
  '/developing-with-nats/receiving': '/using-nats/developing-with-nats/receiving',
  '/developing-with-nats/receiving/async': '/using-nats/developing-with-nats/receiving/async',
  '/developing-with-nats/receiving/drain': '/using-nats/developing-with-nats/receiving/drain',
  '/developing-with-nats/receiving/queues': '/using-nats/developing-with-nats/receiving/queues',
  '/developing-with-nats/receiving/reply': '/using-nats/developing-with-nats/receiving/reply',
  '/developing-with-nats/receiving/structure': '/using-nats/developing-with-nats/receiving/structure',
  '/developing-with-nats/receiving/sync': '/using-nats/developing-with-nats/receiving/sync',
  '/developing-with-nats/receiving/unsub_after': '/using-nats/developing-with-nats/receiving/unsub_after',
  '/developing-with-nats/receiving/unsubscribing': '/using-nats/developing-with-nats/receiving/unsubscribing',
  '/developing-with-nats/receiving/wildcards': '/using-nats/developing-with-nats/receiving/wildcards',
  '/developing-with-nats/reconnect': '/using-nats/developing-with-nats/reconnect',
  '/developing-with-nats/reconnect/buffer': '/using-nats/developing-with-nats/reconnect/buffer',
  '/developing-with-nats/reconnect/disable': '/using-nats/developing-with-nats/reconnect/disable',
  '/developing-with-nats/reconnect/events': '/using-nats/developing-with-nats/reconnect/events',
  '/developing-with-nats/reconnect/max': '/using-nats/developing-with-nats/reconnect/max',
  '/developing-with-nats/reconnect/random': '/using-nats/developing-with-nats/reconnect/random',
  '/developing-with-nats/reconnect/wait': '/using-nats/developing-with-nats/reconnect/wait',
  '/developing-with-nats/security': '/using-nats/developing-with-nats/security',
  '/developing-with-nats/security/creds': '/using-nats/developing-with-nats/security/creds',
  '/developing-with-nats/security/nkey': '/using-nats/developing-with-nats/security/nkey',
  '/developing-with-nats/security/tls': '/using-nats/developing-with-nats/security/tls',
  '/developing-with-nats/security/token': '/using-nats/developing-with-nats/security/token',
  '/developing-with-nats/security/userpass': '/using-nats/developing-with-nats/security/userpass',
  '/developing-with-nats/sending': '/using-nats/developing-with-nats/sending',
  '/developing-with-nats/sending/caches': '/using-nats/developing-with-nats/sending/caches',
  '/developing-with-nats/sending/replyto': '/using-nats/developing-with-nats/sending/replyto',
  '/developing-with-nats/sending/request_reply': '/using-nats/developing-with-nats/sending/request_reply',
  '/developing-with-nats/sending/structure': '/using-nats/developing-with-nats/sending/structure',
  '/developing-with-nats/tutorials': '/using-nats/developing-with-nats/tutorials',
  '/developing-with-nats/tutorials/custom_dialer': '/using-nats/developing-with-nats/tutorials/custom_dialer',
  '/developing-with-nats/tutorials/jwt': '/using-nats/developing-with-nats/tutorials/jwt',
  '/jetstream/concepts': '/using-nats/jetstream/concepts',
  '/developing-with-nats/jetstream': '/using-nats/jetstream/develop_jetstream',
  '/jetstream/getting_started': '/using-nats/jetstream/getting_started',
  '/jetstream/getting_started/using_source': '/using-nats/jetstream/getting_started/using_source',
  '/jetstream/model_deep_dive': '/using-nats/jetstream/model_deep_dive',
  '/jetstream/nats_api_reference': '/using-nats/jetstream/nats_api_reference',
  '/nats-tools/natsbench': '/using-nats/nats-tools/nats CLI/natsbench',
  '/nats-tools/natscli': '/using-nats/nats-tools/nats CLI',
  '/nats-tools/nats_top': '/using-nats/nats-tools/nats_top',
  '/nats-tools/nats_top/nats-top-tutorial': '/using-nats/nats-tools/nats_top/nats-top-tutorial',
  '/nats-tools/nk': '/using-nats/nats-tools/nk',
  '/nats-tools/nsc': '/using-nats/nats-tools/nsc',
  '/nats-tools/nsc/basics': '/using-nats/nats-tools/nsc/basics',
  '/nats-tools/nsc/managed': '/using-nats/nats-tools/nsc/managed',
  '/nats-tools/nsc/revocation': '/using-nats/nats-tools/nsc/revocation',
  '/nats-tools/nsc/services': '/using-nats/nats-tools/nsc/services',
  '/nats-tools/nsc/signing_keys': '/using-nats/nats-tools/nsc/signing_keys',
  '/nats-tools/nsc/streams': '/using-nats/nats-tools/nsc/streams',
  '/nats-tools/nats-tools': '/using-nats/nats-tools',
}
