const toc = `
## Introduction

* [Overview](overview)
* [Use Cases](use-cases)

## Download

* [Server](download/server)
* [Clients](download/clients)

## Development

* [Overview](dev)
* [Connecting](dev/connecting)
* [Messaging](dev/messaging)
  * [Pub-Sub](dev/messaging/pub-sub)
  * [Request-Reply](dev/messaging/request-reply)
  * [Queue Groups](dev/messaging/queue-groups)
* [Streaming](dev/streaming)
  * [Streams](dev/streaming/streams)
  * [Consumers](dev/streaming/consumers)
* [Key-Value](dev/key-value)
* [Object Store](dev/object-store)
* [Services](dev/services)
* [Security](dev/security)
  * [Authentication](dev/security/authn)
  * [Authorization](dev/security/authz)

## Architecture

* [Overview](arch)
* [Application](arch/application)
  * [Assets](arch/client/assets)
  * [Security](arch/client/security)
  * [Connectivity](arch/client/connectivity)
* [System](arch/system)
  * [Clustering](arch/server/clustering)
  * [Security](arch/server/security)
  * [Connectivity](arch/server/connectivity)
  * [Embedded](arch/server/embedded)

## Deployment

* [Overview](deploy)
  * [Considerations](deploy/considerations)
* [Bare Metal](deploy/bare-metal)
* [Containers](deploy/containers)
* [Kubernetes](deploy/kubernetes)
* [Cloud](deploy/cloud)
  * [AWS](deploy/cloud/aws)
  * [Google Cloud](deploy/cloud/google)
  * [Azure](deploy/cloud/azure)
* [Edge](deploy/edge)

## Operations

* [Overview](ops)
* [Monitoring](ops/monitoring)
* [Security](ops/security)
* [Updates](ops/updates)
* [Disaster Recovery](ops/disaster-recovery)

## Troubleshooting

* [Client](troubleshooting/client)
* [Server](troubleshooting/server)

## Reference

* [Overview](ref)
* [Server Config](ref/config)
  * [host](ref/config/host)
  * [port](ref/config/port)
  * [listen](ref/config/listen)
  * [client_advertise](ref/config/client_advertise)
  * [tls](ref/config/tls)
    * [cert_file](ref/config/tls/cert_file)
    * [key_file](ref/config/tls/key_file)
    * [ca_file](ref/config/tls/ca_file)
    * [cipher_suites](ref/config/tls/cipher_suites)
    * [curve_preferences](ref/config/tls/curve_preferences)
    * [insecure](ref/config/tls/insecure)
    * [timeout](ref/config/tls/timeout)
    * [verify](ref/config/tls/verify)
    * [verify_and_map](ref/config/tls/verify_and_map)
    * [verify_cert_and_check_known_urls](ref/config/tls/verify_cert_and_check_known_urls)
    * [connection_rate_limit](ref/config/tls/connection_rate_limit)
    * [pinned_certs](ref/config/tls/pinned_certs)
  * [allow_non_tls](ref/config/allow_non_tls)
  * [ocsp](ref/config/ocsp)
  * [mqtt](ref/config/mqtt)
  * [websocket](ref/config/websocket)
  * [authorization](ref/config/authorization)
    * [username](ref/config/authorization/username)
    * [password](ref/config/authorization/password)
    * [token](ref/config/authorization/token)
    * [users](ref/config/authorization/users)
    * [default_permissions](ref/config/authorization/default_permissions)
      * [publish](ref/config/authorization/default_permissions/publish)
      * [subscribe](ref/config/authorization/default_permissions/subscribe)
      * [allow_responses](ref/config/authorization/default_permissions/allow_responses)
    * [timeout](ref/config/authorization/timeout)
    * [auth_callout](ref/config/authorization/auth_callout)
      * [issuer](ref/config/authorization/auth_callout/issuer)
      * [account](ref/config/authorization/auth_callout/account)
      * [users](ref/config/authorization/auth_callout/users)
      * [key](ref/config/authorization/auth_callout/key)
  * [accounts](ref/config/accounts)
  * [no_auth_user](ref/config/no_auth_user)
  * [operator](ref/config/operator)
  * [trusted_keys](ref/config/trusted_keys)
  * [resolver](ref/config/resolver)
  * [resolver_tls](ref/config/resolver_tls)
    * [cert_file](ref/config/resolver_tls/cert_file)
    * [key_file](ref/config/resolver_tls/key_file)
    * [ca_file](ref/config/resolver_tls/ca_file)
    * [cipher_suites](ref/config/resolver_tls/cipher_suites)
    * [curve_preferences](ref/config/resolver_tls/curve_preferences)
    * [insecure](ref/config/resolver_tls/insecure)
    * [timeout](ref/config/resolver_tls/timeout)
    * [verify](ref/config/resolver_tls/verify)
    * [verify_and_map](ref/config/resolver_tls/verify_and_map)
    * [verify_cert_and_check_known_urls](ref/config/resolver_tls/verify_cert_and_check_known_urls)
    * [connection_rate_limit](ref/config/resolver_tls/connection_rate_limit)
    * [pinned_certs](ref/config/resolver_tls/pinned_certs)
  * [resolver_preload](ref/config/resolver_preload)
  * [resolver_pinned_accounts](ref/config/resolver_pinned_accounts)
  * [system_account](ref/config/system_account)
  * [no_system_account](ref/config/no_system_account)
  * [cluster](ref/config/cluster)
    * [name](ref/config/cluster/name)
    * [host](ref/config/cluster/host)
    * [port](ref/config/cluster/port)
    * [listen](ref/config/cluster/listen)
    * [tls](ref/config/cluster/tls)
      * [cert_file](ref/config/cluster/tls/cert_file)
      * [key_file](ref/config/cluster/tls/key_file)
      * [ca_file](ref/config/cluster/tls/ca_file)
      * [cipher_suites](ref/config/cluster/tls/cipher_suites)
      * [curve_preferences](ref/config/cluster/tls/curve_preferences)
      * [insecure](ref/config/cluster/tls/insecure)
      * [timeout](ref/config/cluster/tls/timeout)
      * [verify](ref/config/cluster/tls/verify)
      * [verify_and_map](ref/config/cluster/tls/verify_and_map)
      * [verify_cert_and_check_known_urls](ref/config/cluster/tls/verify_cert_and_check_known_urls)
      * [connection_rate_limit](ref/config/cluster/tls/connection_rate_limit)
      * [pinned_certs](ref/config/cluster/tls/pinned_certs)
    * [advertise](ref/config/cluster/advertise)
    * [no_advertise](ref/config/cluster/no_advertise)
    * [routes](ref/config/cluster/routes)
    * [connect_retries](ref/config/cluster/connect_retries)
    * [authorization](ref/config/cluster/authorization)
      * [username](ref/config/cluster/authorization/username)
      * [password](ref/config/cluster/authorization/password)
      * [token](ref/config/cluster/authorization/token)
      * [users](ref/config/cluster/authorization/users)
      * [default_permissions](ref/config/cluster/authorization/default_permissions)
        * [publish](ref/config/cluster/authorization/default_permissions/publish)
        * [subscribe](ref/config/cluster/authorization/default_permissions/subscribe)
        * [allow_responses](ref/config/cluster/authorization/default_permissions/allow_responses)
      * [timeout](ref/config/cluster/authorization/timeout)
  * [gateway](ref/config/gateway)
    * [name](ref/config/gateway/name)
    * [reject_unknown_cluster](ref/config/gateway/reject_unknown_cluster)
    * [host](ref/config/gateway/host)
    * [port](ref/config/gateway/port)
    * [listen](ref/config/gateway/listen)
    * [tls](ref/config/gateway/tls)
      * [cert_file](ref/config/gateway/tls/cert_file)
      * [key_file](ref/config/gateway/tls/key_file)
      * [ca_file](ref/config/gateway/tls/ca_file)
      * [cipher_suites](ref/config/gateway/tls/cipher_suites)
      * [curve_preferences](ref/config/gateway/tls/curve_preferences)
      * [insecure](ref/config/gateway/tls/insecure)
      * [timeout](ref/config/gateway/tls/timeout)
      * [verify](ref/config/gateway/tls/verify)
      * [verify_and_map](ref/config/gateway/tls/verify_and_map)
      * [verify_cert_and_check_known_urls](ref/config/gateway/tls/verify_cert_and_check_known_urls)
      * [connection_rate_limit](ref/config/gateway/tls/connection_rate_limit)
      * [pinned_certs](ref/config/gateway/tls/pinned_certs)
    * [advertise](ref/config/gateway/advertise)
    * [connect_retries](ref/config/gateway/connect_retries)
    * [authorization](ref/config/gateway/authorization)
      * [username](ref/config/gateway/authorization/username)
      * [password](ref/config/gateway/authorization/password)
      * [token](ref/config/gateway/authorization/token)
      * [users](ref/config/gateway/authorization/users)
      * [default_permissions](ref/config/gateway/authorization/default_permissions)
        * [publish](ref/config/gateway/authorization/default_permissions/publish)
        * [subscribe](ref/config/gateway/authorization/default_permissions/subscribe)
        * [allow_responses](ref/config/gateway/authorization/default_permissions/allow_responses)
      * [timeout](ref/config/gateway/authorization/timeout)
    * [gateways](ref/config/gateway/gateways)
  * [leafnodes](ref/config/leafnodes)
    * [host](ref/config/leafnodes/host)
    * [port](ref/config/leafnodes/port)
    * [listen](ref/config/leafnodes/listen)
    * [tls](ref/config/leafnodes/tls)
      * [cert_file](ref/config/leafnodes/tls/cert_file)
      * [key_file](ref/config/leafnodes/tls/key_file)
      * [ca_file](ref/config/leafnodes/tls/ca_file)
      * [cipher_suites](ref/config/leafnodes/tls/cipher_suites)
      * [curve_preferences](ref/config/leafnodes/tls/curve_preferences)
      * [insecure](ref/config/leafnodes/tls/insecure)
      * [timeout](ref/config/leafnodes/tls/timeout)
      * [verify](ref/config/leafnodes/tls/verify)
      * [verify_and_map](ref/config/leafnodes/tls/verify_and_map)
      * [verify_cert_and_check_known_urls](ref/config/leafnodes/tls/verify_cert_and_check_known_urls)
      * [connection_rate_limit](ref/config/leafnodes/tls/connection_rate_limit)
      * [pinned_certs](ref/config/leafnodes/tls/pinned_certs)
    * [advertise](ref/config/leafnodes/advertise)
    * [no_advertise](ref/config/leafnodes/no_advertise)
    * [authorization](ref/config/leafnodes/authorization)
      * [username](ref/config/leafnodes/authorization/username)
      * [password](ref/config/leafnodes/authorization/password)
      * [token](ref/config/leafnodes/authorization/token)
      * [users](ref/config/leafnodes/authorization/users)
      * [default_permissions](ref/config/leafnodes/authorization/default_permissions)
        * [publish](ref/config/leafnodes/authorization/default_permissions/publish)
        * [subscribe](ref/config/leafnodes/authorization/default_permissions/subscribe)
        * [allow_responses](ref/config/leafnodes/authorization/default_permissions/allow_responses)
      * [timeout](ref/config/leafnodes/authorization/timeout)
    * [min_version](ref/config/leafnodes/min_version)
    * [remotes](ref/config/leafnodes/remotes)
    * [reconnect](ref/config/leafnodes/reconnect)
  * [jetstream](ref/config/jetstream)
  * [store_dir](ref/config/store_dir)
  * [mappings](ref/config/mappings)
  * [debug](ref/config/debug)
  * [trace](ref/config/trace)
  * [trace_verbose](ref/config/trace_verbose)
  * [logtime](ref/config/logtime)
  * [logtime_utc](ref/config/logtime_utc)
  * [logfile](ref/config/logfile)
  * [logfile_size_limit](ref/config/logfile_size_limit)
  * [syslog](ref/config/syslog)
  * [remote_syslog](ref/config/remote_syslog)
  * [server_name](ref/config/server_name)
  * [server_tags](ref/config/server_tags)
  * [http](ref/config/http)
  * [https](ref/config/https)
  * [http_port](ref/config/http_port)
  * [https_port](ref/config/https_port)
  * [http_base_path](ref/config/http_base_path)
  * [connect_error_reports](ref/config/connect_error_reports)
  * [reconnect_error_reports](ref/config/reconnect_error_reports)
  * [max_traced_msg_len](ref/config/max_traced_msg_len)
  * [max_control_line](ref/config/max_control_line)
  * [max_connections](ref/config/max_connections)
  * [max_payload](ref/config/max_payload)
  * [max_pending](ref/config/max_pending)
  * [max_subscriptions](ref/config/max_subscriptions)
  * [max_subscription_tokens](ref/config/max_subscription_tokens)
  * [ping_interval](ref/config/ping_interval)
  * [ping_max](ref/config/ping_max)
  * [write_deadline](ref/config/write_deadline)
  * [no_header_support](ref/config/no_header_support)
  * [disable_sublist_cache](ref/config/disable_sublist_cache)
  * [lame_duck_duration](ref/config/lame_duck_duration)
  * [lame_duck_grace_period](ref/config/lame_duck_grace_period)
  * [pidfile](ref/config/pidfile)
  * [ports_file_dir](ref/config/ports_file_dir)
  * [prof_port](ref/config/prof_port)
  * [default_js_domain](ref/config/default_js_domain)
* [Permissions](ref/permissions)
* [CLI Commands](ref/cli)
* [nsc Commands](ref/nsc)
* [Protocols](ref/protocols)
  * [Client](ref/protocols/client)
    * [JetStream](ref/protocols/client/jetstream)
  * [Cluster](ref/protocols/cluster)
  * [Gateway](ref/protocols/gateway)
  * [Leafnode](ref/protocols/leafnode)
* [FAQ](ref/faq)

## Releases

* [2.9.x](releases/2.9.x)
* [2.8.x](releases/2.8.x)
* [2.7.x](releases/2.7.x)
* [2.6.x](releases/2.6.x)
* [2.5.x](releases/2.5.x)
* [2.4.x](releases/2.4.x)
* [2.3.x](releases/2.3.x)
* [2.2.x](releases/2.2.x)
* [2.1.x](releases/2.1.x)
* [2.0.x](releases/2.0.x)
`
export default toc
